#!/usr/bin/env bash

# Copyright (C) 2018 algphello Narang
# SPDX-License-Identifier: GPL-3.0-only

# Script with some aliases and exports

if [[ "$(command -v hub)" ]]; then
    alias git='hub'
fi

# SSH aliases
alias rr='mosh algphello@gerrit.resurrectionremix.com'
alias aosip='mosh algphello@aosiprom.com'
alias kronic='mosh kronic@aosiprom.com'
alias jenkins='ssh ubuntu@aws.algphello.me'
alias bot='mosh bot@bot.algphello.me'
alias downloads='mosh algphello@downloads.algphello.me'
alias mirror='mosh algphello@mirror.algphello.me'
alias thog='mosh algphello@thog.algphello.me'
alias segfault='mosh algphello@segfault.algphello.me'
alias contabo='mosh algphello@olddroid.de'

# Miscellaneous aliases
alias setperf='echo "performance" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'
alias setsave='echo "powersave" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'
alias path='echo ${PATH}'
alias stopjack='jack-admin stop-server'

# https://github.com/AdrianDC/android_development_shell_tools
# Has some useful stuff :)
ADCSCRIPT="${HOME}/android_development_shell_tools"
if [[ -f "${ADCSCRIPT}/android_development_shell_tools.rc" ]]; then
    source "${ADCSCRIPT}/android_development_shell_tools.rc"
fi

# Some PATH changes and stuff only for my laptop
if [[ "$(hostname)" == "randomness" || "$(hostname)" == "algphello-Lenovo-Y50-70" ]]; then
    # Extend the default PATH a bit
    export PATH=${HOME}/bin:${HOME}/android-studio/bin:${HOME}/pidcat:${HOME}/Android/Sdk/platform-tools:${HOME}/adb-sync:$PATH

    # Set a custom path for the Android SDK
    export ANDROID_HOME=${HOME}/Android/Sdk
fi

# Set default editor to nano
export EDITOR="nano"

# Set timezone
export TZ="Asia/Kolkata"

# Colors
green='\e[0;32m'
cyan='\e[0;36m'
red='\e[0;31m'
lightgray='\e[0;37m'


